---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: lxd
lint: |
    yamllint .
    ansible-lint --exclude meta .git
    flake8

platforms:
  - name: "polycomprosrv-${MOLECULE_DISTRIBUTION:-ubuntu-focal}"
    alias: "${MOLECULE_IMAGE:-ubuntu/focal}"

provisioner:
  name: ansible
  playbooks:
    create: ../resources/playbooks/create.yml
    converge: ../resources/playbooks/converge.yml
    destroy: ../resources/playbooks/destroy.yml
  options:
    vvv: true

scenario:
  name: default
verifier:
  name: testinfra
  directory: ../resources/tests/
  options:
    verbose: true
