---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
    yamllint .
    ansible-lint --exclude meta .git
    flake8

platforms:
  - name: polycom-prosrv_${MOLECULE_DISTRIBUTION:-ubuntu18}
    image: "quay.io/samdoran/${MOLECULE_DISTRIBUTION:-ubuntu18}-ansible:latest"
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    published_ports:
      - "21:21/tcp"
      - "20:20/tcp"
      - "60000-60100:60000-60100/tcp"
    privileged: true
    pre_build_image: yes
provisioner:
  name: ansible
  options:
    vvv: true

scenario:
  name: default
verifier:
  name: testinfra
  options:
    verbose: true
