---
- name: Converge
  hosts: all
  # setup vsftpd
  pre_tasks:
    - name: Include test variables
      include_vars:
        file: test-vars.yml
      when: polycom_ci_test|default(true)

    - name: Include production test variables
      include_vars:
        file: production-vars.yml
      when: not polycom_ci_test|default(true)

    - name: Update repo cache
      action: >
        {{ ansible_pkg_mgr }} update_cache=yes

  # Setup vsftp for provisioning
  tasks:
    - name: Setup polycom provisioning
      include_role:
        name: ansible-polycom-prosrv
